<?xml version = "1.0" encoding="UTF-8"?>

<!DOCTYPE students[
<!ELEMENT students (student+)>
<!ELEMENT student (id, name, department, batch)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT batch (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

<!ATTLIST student id CDATA #IMPLIED>
]>

<students>
  <student id = "1221">
    <id>1011</id>
    <name>rija</name>
    <department>computerscience</department>
    <batch>AI-202408E1</batch>
  </student>

  <student id = "1222">
    <id>1012</id>
    <name>Yumna</name>
    <department>computer science</department>
    <batch>AI-202408E1</batch>
  </student>
</students>

<